language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

install:
  - composer install

script:
  - bin/phpunit
  - bin/behat
  - bin/behat --profile=expressive
